# Generated by Django 4.1.3 on 2022-12-14 16:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', phone_field.models.PhoneField(help_text='Contact Phone number', max_length=31)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', phone_field.models.PhoneField(help_text='Contact Phone number', max_length=31)),
                ('drink', models.CharField(blank=True, choices=[('ca phe', 'Cà phê'), ('black coffee', 'Black Coffee'), ('latte', 'Latte'), ('macchiato', 'Macchiato'), ('cappucchino', 'Cappucchino'), ('cortado', 'Cortado'), ('cold brew', 'Cold Brew'), ('lemonade', 'Lemonade'), ('hot chocolate', 'Hot Chocolate'), ('tea', 'Tea'), ('thai iced tea', 'Thai Iced Tea')], max_length=30, null=True)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xtra', 'Xtra Large')], max_length=30, null=True)),
                ('style', models.CharField(blank=True, choices=[('hot', 'Hot'), ('ice', 'Iced')], max_length=30, null=True)),
                ('sugar', models.CharField(blank=True, choices=[('none', 'None'), ('less', 'Less'), ('regular', 'Regular'), ('extra', 'Extra')], max_length=30, null=True)),
                ('ice', models.CharField(blank=True, choices=[('none', 'None'), ('less', 'Less'), ('regular', 'Regular'), ('extra', 'Extra')], max_length=30, null=True)),
                ('snack', models.CharField(blank=True, choices=[('chocolate', 'Chocolate Donut'), ('plain', 'Plain Donut'), ('sugar', 'Sugar Donut'), ('che thai', 'Chè Thái'), ('banh bao', 'Bánh bao'), ('banh cam', 'Bánh Cam')], max_length=30, null=True)),
                ('message', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.AlterModelTable(
            name='subscribe',
            table='Subscribe',
        ),
    ]
